version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: foyerMassoudFardi
      MYSQL_USER: utilisateur
      MYSQL_PASSWORD: motdepasse
    ports:
      - "3306:3306"
    networks:
      - app-network

  spring-app:
    build:
      context: .
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: utilisateur
      DB_PASSWORD: motdepasse
    ports:
      - "8412:8412"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
