version: '3.8'
networks:
  mynetwork:
    driver: bridge

services:
  # MySQL database service
  mysql:
    image: mysql:8.0
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: foyer
      MYSQL_USER: utilisateur
      MYSQL_PASSWORD: motdepasse
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Spring Boot application service
  app:
    image: medkhoualdia/foyer:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    networks:
      - mynetwork
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/foyer?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: utilisateur
      SPRING_DATASOURCE_PASSWORD: motdepasse
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: '*'
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: 'true'
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: 'true'
  # PHPMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - mynetwork
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: utilisateur
      PMA_PASSWORD: motdepasse


volumes:
  mysql-data: